// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr4HooABYAjrjyYNnOU4fqEsHRmV7IuOk',
    appId: '1:551629422776:web:b4a35c1add2823edfa744d',
    messagingSenderId: '551629422776',
    projectId: 'seguridadlogin-fcc47',
    authDomain: 'seguridadlogin-fcc47.firebaseapp.com',
    storageBucket: 'seguridadlogin-fcc47.firebasestorage.app',
    measurementId: 'G-VBD3ZTNZ5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQStM2MNUMHZx9FFIPQEicssjdpPyMDQY',
    appId: '1:551629422776:android:8f1a85f0530c2ecdfa744d',
    messagingSenderId: '551629422776',
    projectId: 'seguridadlogin-fcc47',
    storageBucket: 'seguridadlogin-fcc47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYNLRjA7CruhhSP8Hc8Lfzf7x3XVbyqdY',
    appId: '1:551629422776:ios:b23b7c0d9b72218dfa744d',
    messagingSenderId: '551629422776',
    projectId: 'seguridadlogin-fcc47',
    storageBucket: 'seguridadlogin-fcc47.firebasestorage.app',
    iosBundleId: 'com.ameth.seguridad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYNLRjA7CruhhSP8Hc8Lfzf7x3XVbyqdY',
    appId: '1:551629422776:ios:b23b7c0d9b72218dfa744d',
    messagingSenderId: '551629422776',
    projectId: 'seguridadlogin-fcc47',
    storageBucket: 'seguridadlogin-fcc47.firebasestorage.app',
    iosBundleId: 'com.ameth.seguridad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr4HooABYAjrjyYNnOU4fqEsHRmV7IuOk',
    appId: '1:551629422776:web:06b60f36e2ca6d09fa744d',
    messagingSenderId: '551629422776',
    projectId: 'seguridadlogin-fcc47',
    authDomain: 'seguridadlogin-fcc47.firebaseapp.com',
    storageBucket: 'seguridadlogin-fcc47.firebasestorage.app',
    measurementId: 'G-6E4Q2EQD9B',
  );
}
